export const ROAD_WIDTH_PRESETS = [
  { key: 'custom', label: 'Custom / override', realM: null },
  { key: 'service_alley', label: 'Service alley', realM: 3.0 },
  { key: 'one_lane_local', label: 'One-lane local road', realM: 4.0 },
  { key: 'residential_street', label: 'Residential street', realM: 5.5 },
  { key: 'two_lane_local', label: 'Two-lane local street', realM: 6.0 },
  { key: 'collector_street', label: 'Collector street', realM: 7.0 },
  { key: 'main_street', label: 'Main street', realM: 9.0 },
  { key: 'industrial_service', label: 'Industrial/service road', realM: 10.5 },
];

export const SIDEWALK_WIDTH_PRESETS = [
  { key: 'custom', label: 'Custom / override', realM: null },
  { key: 'narrow', label: 'Narrow sidewalk', realM: 1.2 },
  { key: 'standard', label: 'Standard sidewalk', realM: 1.5 },
  { key: 'comfortable', label: 'Comfortable sidewalk', realM: 2.0 },
  { key: 'commercial', label: 'Commercial sidewalk', realM: 3.0 },
  { key: 'wide_plaza', label: 'Wide sidewalk / plaza edge', realM: 4.0 },
];

export const BUILDING_STATES = {
  notStarted: 'Not Started',
  inProgress: 'In Progress',
  awaitingConstruction: 'Awaiting Construction',
  complete: 'Complete',
};

export const TRACK_PROFILE_DEFAULTS = Object.freeze({
  gaugeMm: 9,
  railWidthMm: 0.55,
  railHeightMm: 0.8,
  tieSpacingMm: 4,
  tieLengthMm: 16,
  tieWidthMm: 1.3,
  roadbedWidthMm: 19,
  roadbedHeightMm: 2.5,
  roadbedShoulderMm: 3.5,
  roadbedColor: '#c7b084',
  roadbedTopColor: '#d8c79c',
  railColor: '#3b3832',
  tieColor: '#8a6f43',
  reference: 'N gauge 9 mm track; 19 mm cork roadbed profile documented in docs/site-planner-track-profile.md.',
});

export const JP_ROAD_MARKING_STANDARD_ID = 'JP_Order_on_Road_Signs_Road_Lines_and_Road_Surface_Markings_1960';

export const FABRIC_PRESETS = {
  lowRiseResidentialFabric: {
    label: 'Low-Rise Residential Fabric',
    types: ['smallHouse', 'smallHouse', 'apartment', 'shopHouse'],
    floors: [1, 2, 3],
    lotW: [18, 38],
    depth: [22, 55],
    commercial: 0.12,
    signage: 0.12,
    detail: 0.35,
  },
  localMixedUseFabric: {
    label: 'Local Mixed-Use Fabric',
    types: ['shopHouse', 'shopHouse', 'workshopHouse', 'apartment', 'restrainedZakkyo'],
    floors: [2, 3, 4],
    lotW: [22, 45],
    depth: [30, 70],
    commercial: 0.65,
    signage: 0.35,
    detail: 0.55,
  },
  edgeEnclosedPocketFabric: {
    label: 'Edge-Enclosed Pocket Fabric',
    types: ['apartment', 'officeBlock', 'zakkyo', 'smallHouse', 'shopHouse'],
    floors: [2, 3, 5, 6],
    lotW: [25, 55],
    depth: [28, 75],
    commercial: 0.45,
    signage: 0.35,
    detail: 0.55,
  },
  stationCommercialStack: {
    label: 'Station Commercial Stack',
    types: ['zakkyo', 'officeBlock', 'stackedCommercialBuilding', 'shopHouse'],
    floors: [4, 6, 8, 10],
    lotW: [18, 36],
    depth: [35, 85],
    commercial: 0.9,
    signage: 0.75,
    detail: 0.85,
  },
  shopWorkshopStreet: {
    label: 'Shop-Workshop Street',
    types: ['workshopHouse', 'shopHouse', 'warehouse', 'smallOffice'],
    floors: [2, 3, 4, 5],
    lotW: [28, 60],
    depth: [35, 90],
    commercial: 0.55,
    signage: 0.3,
    detail: 0.55,
  },
  signHeavyCommercialCanyon: {
    label: 'Sign-Heavy Commercial Canyon',
    types: ['zakkyo', 'signCoveredTenantStack', 'stackedCommercialBuilding'],
    floors: [6, 8, 10, 12],
    lotW: [16, 34],
    depth: [42, 95],
    commercial: 1,
    signage: 1,
    detail: 1,
  },
  midRiseMixedUseStreet: {
    label: 'Mid-Rise Mixed-Use Street',
    types: ['restrainedZakkyo', 'shopHouse', 'smallOffice', 'apartment'],
    floors: [3, 4, 5, 6, 8],
    lotW: [22, 44],
    depth: [35, 80],
    commercial: 0.65,
    signage: 0.45,
    detail: 0.7,
  },
  perimeterLanewayBlock: {
    label: 'Perimeter Laneway Block',
    types: ['perimeterTenantBlock', 'alleyTenantCell', 'barAlleyUnit', 'tinyRestaurant'],
    floors: [1, 2, 3, 6, 8],
    lotW: [14, 34],
    depth: [20, 65],
    commercial: 0.9,
    signage: 0.65,
    detail: 0.9,
  },
  underViaductInfill: {
    label: 'Under-Viaduct Infill',
    types: ['undertrackBay'],
    floors: [1, 2],
    lotW: [18, 28],
    depth: [18, 42],
    commercial: 0.75,
    signage: 0.5,
    detail: 0.75,
  },
  industrialServiceFabric: {
    label: 'Industrial Service Fabric',
    types: ['warehouse', 'workshopHouse', 'officeBlock', 'serviceBuilding'],
    floors: [1, 2, 3, 4],
    lotW: [45, 110],
    depth: [45, 130],
    commercial: 0.25,
    signage: 0.15,
    detail: 0.45,
  },
};
