export const AUTOSAVE_KEY = 'hakomachiSitePlannerAutosave_v1';
export const AUTOSAVE_META_KEY = 'hakomachiSitePlannerAutosaveMeta_v1';
export const GITHUB_CURRENT_KEY = 'hakomachi_site_planner_github_current_v1';

export function createInitialState() {
  return {
    tool: 'select',
    image: null,
    imageMeta: null,
    imageOpacity: 0.75,
    imageLocked: true,
    view: { x: 0, y: 0, scale: 1 },
    pxPerMm: null,
    calibrationLine: null,
    lastCalibrationLine: null,
    buildings: [],
    selectedId: null,
    selectedIds: [],
    selectedSiteObjects: [],
    hoverBuildingId: null,
    drag: null,
    hover: null,
    polygonDraft: [],
    measureLine: null,
    projectName: 'hakomachi-site',
    roads: [],
    selectedRoadId: null,
    hoverRoadId: null,
    hoverRoadSegment: null,
    roadOutlineEditId: null,
    workspaceMode: 'layout',
    roadMode: 'centerline',
    roadTask: null,
    roadDraft: [],
    tracks: [],
    selectedTrackId: null,
    selectedTrackPointIndex: null,
    hoverTrackId: null,
    trackTask: null,
    trackAccessories: [],
    selectedTrackAccessoryId: null,
    hoverTrackAccessoryId: null,
    trackDraft: [],
    trackDraftExtension: null,
    roadFeatures: [],
    selectedRoadFeatureId: null,
    hoverRoadFeatureId: null,
    roadDrivingSide: 'left',
    roadIntersectionDetails: true,
    roadIntersectionOverrides: {},
    generatedRoadIntersections: [],
    selectedRoadIntersectionId: null,
    generatedRailCrossings: [],
    railCrossingOverrides: {},
    selectedRailCrossingId: null,
    benchworkOutlines: [],
    selectedBenchworkId: null,
    hoverBenchworkId: null,
    hoverBenchworkSegment: null,
    benchworkDraft: [],
    fabricRegions: [],
    selectedFabricId: null,
    fabricDraft: [],
    fabricPreset: 'localMixedUseFabric',
    stlObjects: [],
    selectedStlObjectId: null,
    hoverStlObjectId: null,
    roadExportPreview: false,
    roadExportSettings: { maxPieceMm: 120, avoidJunctionMm: 18, minPieceMm: 35 },
    roadExportReviewOpen: false,
    roadExportReviewSettings: null,
    streetlights: [],
    selectedStreetlightId: null,
    hoverStreetlightId: null,
    streetlightMode: 'free',
    footprintClipboard: null,
    pasteOffsetCount: 0,
    siteObjectClipboard: null,
    siteObjectPasteOffsetCount: 0,
    objectClipboardType: null,
    inputMode: 'penDrawFingerPan',
    shiftKeyDown: false,
    snapOn: false,
    pointers: new Map(),
    pinch: null,
    annotations: [],
    selectedAnnotationId: null,
    hoverPreview: null,
    longPress: null,
    contextTarget: null,
    sidebarOpen: false,
    viewMode: '2d',
    site3d: { imageVisible: true, imageOpacity: 0.45 },
    autosaveReady: false,
    autosaveRestored: false,
    dirty: false,
    dirtySinceManualSave: false,
    lastAutosaveAt: null,
    history: [],
    historyIndex: -1,
    historySuppressed: false,
  };
}
